name: Terraform CD

on:
  push:
    branches:
    - main

# Declare the running agent.
jobs:
  terraform-cd:
    runs-on: ubuntu-latest
    steps:
    # git clone/git checkout.
    - name: Checkout repository
      uses: actions/checkout@v2
    # aws configure.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # or hardcode us-east-1
    # install terraform.
    - name: Terraform Set up
      uses: hashicorp/setup-terraform@v1
    # terraform init.
    - name: Terraform Initialize
      run: terraform init
    - name: Terraform Format
      run: terraform fmt
    - name: Terraform Validate
      run: terraform validate -no-color
    # No need terraform plan for CD process.
    # - name: Terraform Plan
    #   run: terraform plan
    # - name: Terraform Destroy XXXX
    #  run: terraform destroy --auto-approve